b8:
  database:
    servers:
      read:  localhost
      write: localhost
    port:     3306
    name:     php-censor-db
    username: php-censor-user
    password: php-censor-password
php-censor:
  language: en
  per_page: 10
  url:      'http://php-censor.local'
  email_settings:
    from_address: 'no-reply@php-censor.local'
    smtp_address:
  worker:
    host:  localhost
    queue: php-censor-queue
  github:
    token: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
    comments:
      commit:       false
      pull_request: false
  authentication_settings:
    state:   false
    user_id: 1